
package pl.edu.agh.soa.lab1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManageStudents", targetNamespace = "https://www.soa.lab.agh.edu.pl/lab1", wsdlLocation = "http://localhost:8080/lab1-soap?wsdl")
public class ManageStudents_Service
    extends Service
{

    private final static URL MANAGESTUDENTS_WSDL_LOCATION;
    private final static WebServiceException MANAGESTUDENTS_EXCEPTION;
    private final static QName MANAGESTUDENTS_QNAME = new QName("https://www.soa.lab.agh.edu.pl/lab1", "ManageStudents");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab1-soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGESTUDENTS_WSDL_LOCATION = url;
        MANAGESTUDENTS_EXCEPTION = e;
    }

    public ManageStudents_Service() {
        super(__getWsdlLocation(), MANAGESTUDENTS_QNAME);
    }

    public ManageStudents_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGESTUDENTS_QNAME, features);
    }

    public ManageStudents_Service(URL wsdlLocation) {
        super(wsdlLocation, MANAGESTUDENTS_QNAME);
    }

    public ManageStudents_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGESTUDENTS_QNAME, features);
    }

    public ManageStudents_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageStudents_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManageStudents
     */
    @WebEndpoint(name = "HelloStudentsPort")
    public ManageStudents getHelloStudentsPort() {
        return super.getPort(new QName("https://www.soa.lab.agh.edu.pl/lab1", "HelloStudentsPort"), ManageStudents.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageStudents
     */
    @WebEndpoint(name = "HelloStudentsPort")
    public ManageStudents getHelloStudentsPort(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.soa.lab.agh.edu.pl/lab1", "HelloStudentsPort"), ManageStudents.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGESTUDENTS_EXCEPTION!= null) {
            throw MANAGESTUDENTS_EXCEPTION;
        }
        return MANAGESTUDENTS_WSDL_LOCATION;
    }

}
